server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true